default_platform :ios

platform :ios do
  before_all do
    clear_derived_data
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      workspace: 'iOS-ApplicationTemplate.xcworkspace',
      scheme: 'iOS-ApplicationTemplate',
      clean: true,
      skip_build: true,
      code_coverage: true
    )

    xcov(
      workspace: 'iOS-ApplicationTemplate.xcworkspace',
      scheme: 'iOS-ApplicationTemplate'
    )
  end
end
